### PR TITLE
Ordered by code

### PR DESCRIPTION
**Pull request by iRaiko**
I have ordered all of the files by the code of the button/axis/trigger/three_way using a small script (w.i.p.)

### CODE REVIEW

**Comment by Nezeky** [comment]
@iRaiko Hi, thanks for the PR!  Is there any way to configure your script to use double quotes instead of single quotes in the TOML?  I don't really want to change the style, otherwise looks perfect!  I also wouldn't mind having a copy of the script as part of the PR if you don't mind sharing it, even if it's very WIP.

**Comment by iRaiko** [comment]
@Nezeky No problems! I have fixed the single quotes, I didn't notice it was putting them in as singles. And I'm happy to share it. Though I'm not entirely sure how, still being a bit new to working like this.

**Comment by Nezeky** [comment]
@iRaiko Thanks!

You can share it by putting your script inside the "stick/" folder on your computer, running `git add SCRIPT_NAME` (replacing SCRIPT_NAME with the name of your script), then committing and pushing it to your fork of stick.  I believe then it will show up as part of this PR, and I can include it in the repository when I merge the PR.

**Comment by iRaiko** [comment]
@Nezeky It's a commandline thing, i made with clap. For now it's only use is the ordering of the file (or files if you give the directory) with an exclude of file name starts.
So usage would be stick_script.exe order <file/dir> x
to ignore files starting with an x
Will upload it to my github later so you can check out the code and stuff

**Comment by Nezeky** [comment]
I just realized there might be a bug in your script.  It removed one of the mappings in pad_db/pad/mapping/xxxx38071817xxxx.toml, can you try and fix the bug?

**Comment by Nezeky** [comment]
@iRaiko I unfortunately had to revert the merge, since the database was corrupted.  I also added a new file "fmt_db.rs".  I just discovered the [rust-script](https://rust-script.org) project which seems perfect for this use.  Basically, you can turn your crate into an actual script:

```bash
# To install rust-script
cargo install --force rust-script
# To run the fmt_db.rs script written in Rust at
rust-script fmt_db
```

and the actual fmt_db.rs file looks like:
```rust
//! ```cargo
//! [dependencies]
//! # put your Cargo dependencies here
//! ```
fn main() {
    todo!()
}
```

Can you convert your script to work with rust-script and open a new PR?  If so, that would be awesome!  I'll accept the script with or without the bug fix.

**Pull request merged**
